version: '3.4'

services:
  mpcparty:
    build:
      context: .
    ports:
      - 8081:8081
    volumes:
      - ./mpcparty.cfg:/app/mpcparty.cfg
      - ~/Music:/music  # change me! (the "~/Music" part if necessary)
