name: MPCParty CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Installing dependencies...
      run: yarn install
    - name: Checking formatting...
      run: yarn lint
    - name: Removing devel dependencies for release...
      run: yarn install --production
    - run: cp mpcparty.cfg.example mpcparty.cfg
    - uses: actions/upload-artifact@v2
      with:
        name: MPCParty-${{ matrix.os }}
        path: .
